---

- name: ensure AD feature is enabled
  win_feature:
    name: AD-Domain-Services
    state: present

- name: Ensure the named domain is reachable from the target host; if not, create the domain in a new forest residing on the target host
  win_domain:
    dns_domain_name: "{{ ad_domain_name }}"
    safe_mode_password: "{{ ad_safe_password }}"
  register: win_ad_install_register_install  
  ignore_errors: true

- name: Debug
  debug:
    var: win_ad_install_register_install

- name: reboot Windows
  win_reboot:
  when: win_ad_install_register_install.failed  or win_ad_install_register_install.reboot_required

- name: Get the domain list available
  win_command: nltest /dclist:"{{ ad_domain_name }}"
  register: win_ad_install_register_domainlist
  changed_when: false

- name: Print domain list
  debug:
    var: win_ad_install_register_domainlist
