---

- name: ensure haproxy is started
  service:
    name: haproxy
    state: started
    enabled: yes

- name: ensure haproxy config is up to date
  template:
    src: etc/haproxy/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart haproxy

 
