#!/bin/bash

[ $# -ne 1 ] && echo "Usage: `basename $0` role" && exit 1

role=$1
ansible-galaxy init $role

cat > ${role}/tasks/main.yml << EOT
---

- name: include os specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_distibution }}_{{ ansible_distribution_version }}.yml'
    - '{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml'
    - '{{ ansible_os_family }}.yml'
  tags:
    - 'role::${role}'
    - 'role::${role}:install'
    - 'role::${role}:config'

- name: include installation tasks
  import_tasks: installation.yml
  tags:
    - 'role::${role}'
    - 'role::${role}:install'

- import_tasks: configuration.yml
  tags:
    - 'role::${role}'
    - 'role::${role}:config'
EOT

echo "---" > ${role}/tasks/installation.yml
echo "---" > ${role}/tasks/configuration.yml

